os:
  - linux

language: c

cache:
  directories:
    - "$HOME/.nimble"
    - "$HOME/.choosenim"

addons:
  firefox: "73.0"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install autoconf libtool
  - git clone -b 3.5.4 https://github.com/sass/libsass.git
  - cd libsass
  - autoreconf --force --install
  - |
      ./configure \
        --disable-tests \
        --disable-static \
        --enable-shared \
        --prefix=/usr
  - sudo make -j5 install
  - cd ..

  - wget https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.26.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver

install:
  - export CHOOSENIM_CHOOSE_VERSION="stable"
  - |
      curl https://nim-lang.org/choosenim/init.sh -sSf > init.sh
      sh init.sh -y
  - export PATH=$HOME/.nimble/bin:$PATH
  - nimble refresh -y

script:
  - export MOZ_HEADLESS=1
  - nimble -y install
  - nimble -y test
